*Navigate Project
*DeleteAllObjects
*Action New
*FillForm
 Name = eXpandFramework
*Action Contributors.New
*FillForm
 Name = Tolis Bekiaris
*Action Save and Close
*Action Save and Close

*Action New
*FillForm
 Name = Project2
*Action Contributors.New
*FillForm
 Name = Contributor
*Action Save and Close
*Action Developers
*Action Developers.New
*FillForm
 Name = Developer
*Action Save and Close
*Action Save and Close
