//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpand.ExpressApp.ImportWizard.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpand.ExpressApp.ImportWizard.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExcelImportWizard_BgWorkerRunWorkerCompleted_Error {
            get {
                return ResourceManager.GetString("ExcelImportWizard_BgWorkerRunWorkerCompleted_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Details: .
        /// </summary>
        internal static string ExcelImportWizard_BgWorkerRunWorkerCompleted_Error__Details__ {
            get {
                return ResourceManager.GetString("ExcelImportWizard_BgWorkerRunWorkerCompleted_Error__Details__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has been cancelled.
        /// </summary>
        internal static string ExcelImportWizard_BgWorkerRunWorkerCompleted_The_task_has_been_cancelled {
            get {
                return ResourceManager.GetString("ExcelImportWizard_BgWorkerRunWorkerCompleted_The_task_has_been_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has been completed. Results: .
        /// </summary>
        internal static string ExcelImportWizard_BgWorkerRunWorkerCompleted_The_task_has_been_completed__Results__ {
            get {
                return ResourceManager.GetString("ExcelImportWizard_BgWorkerRunWorkerCompleted_The_task_has_been_completed__Results" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Canceled.
        /// </summary>
        internal static string ExcelImportWizard_BgWorkerRunWorkerCompleted_Work_Canceled {
            get {
                return ResourceManager.GetString("ExcelImportWizard_BgWorkerRunWorkerCompleted_Work_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectSpace cannot be NULL.
        /// </summary>
        internal static string ExcelImportWizard_ExcelImportWizard_ObjectSpace_cannot_be_NULL {
            get {
                return ResourceManager.GetString("ExcelImportWizard_ExcelImportWizard_ObjectSpace_cannot_be_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files(*.xlsx)|*.xlsx.
        /// </summary>
        internal static string ExcelImportWizard_FileSelectEdit_ButtonClick_Excel_Files___xlsx____xlsx {
            get {
                return ResourceManager.GetString("ExcelImportWizard_FileSelectEdit_ButtonClick_Excel_Files___xlsx____xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import excell rows progress....
        /// </summary>
        internal static string ExcelImportWizard_ImportButton_Click_Import_excell_rows_progress___ {
            get {
                return ResourceManager.GetString("ExcelImportWizard_ImportButton_Click_Import_excell_rows_progress___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate column names found, please fix excel column names.
        /// </summary>
        internal static string ExcelImportWizard_InitWizPage1_Duplicate_column_names_found__please_fix_excel_column_names {
            get {
                return ResourceManager.GetString("ExcelImportWizard_InitWizPage1_Duplicate_column_names_found__please_fix_excel_col" +
                        "umn_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing record {0}. {1}.
        /// </summary>
        internal static string ExcelImportWizard_ProccesExcellRows_Error_processing_record__0____1_ {
            get {
                return ResourceManager.GetString("ExcelImportWizard_ProccesExcellRows_Error_processing_record__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing record {0} succesfull..
        /// </summary>
        internal static string ExcelImportWizard_ProccesExcellRows_Importing_record__0__succesfull_ {
            get {
                return ResourceManager.GetString("ExcelImportWizard_ProccesExcellRows_Importing_record__0__succesfull_", resourceCulture);
            }
        }
    }
}
