#DropDB XpandSystemTesterEasyTest
#Application XpandSystemTester.Win

*UseModel
#IncludeFile ..\Login.inc
*Action Navigation(Default.Actions Object)

#IncludeFile .\Change Action item visibility from model.inc
#IncludeFile .\Create action item from model.inc
#IncludeFile .\Use a new action item to modify model .inc
#IncludeFile .\Lock View Model.inc
#IncludeFile .\Configure View Model.inc
#IncludeFile .\Reset View Model.inc



