call buildproject.cmd Xpand.Utils ".\Xpand\Xpand.Utils\Xpand.Utils.csproj"
call buildproject.cmd Xpand.ExpressApp.EmailTemplateEngine ".\Xpand\Xpand.ExpressApp.Modules\EmailTemplateEngine\Xpand.EmailTemplateEngine.csproj"
call buildproject.cmd Xpand.Xpo ".\Xpand\Xpand.Xpo\Xpand.Xpo.csproj"
call buildproject.cmd Xpand.Persistent.Base ".\Xpand\Xpand.Persistent\Xpand.Persistent.Base\Xpand.Persistent.Base.csproj"
call buildproject.cmd Xpand.ExpressApp ".\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.ExpressApp.csproj"
call buildproject.cmd Xpand.ExpressApp.Win ".\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.Web ".\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.Security ".\Xpand\Xpand.ExpressApp.Modules\Security\Xpand.ExpressApp.Security.csproj"
call buildproject.cmd Xpand.ExpressApp.Validation ".\Xpand\Xpand.ExpressApp.Modules\Validation\Xpand.ExpressApp.Validation.csproj"
call buildproject.cmd Xpand.ExpressApp.Logic ".\Xpand\Xpand.ExpressApp.Modules\Logic\Xpand.ExpressApp.Logic.csproj"
call buildproject.cmd Xpand.ExpressApp.Logic.Win ".\Xpand\Xpand.ExpressApp.Modules\Logic.Win\Xpand.ExpressApp.Logic.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.Logic.Conditional ".\Xpand\Xpand.ExpressApp.Modules\Logic.Conditional\Xpand.ExpressApp.Logic.Conditional.csproj"
call buildproject.cmd Xpand.ExpressApp.MemberLevelSecurity ".\Xpand\Xpand.ExpressApp.Modules\MemberLevelSecurity\Xpand.ExpressApp.MemberLevelSecurity.csproj"
call buildproject.cmd Xpand.ExpressApp.MemberLevelSecurity.Win ".\Xpand\Xpand.ExpressApp.Modules\MemberLevelSecurity.Win\Xpand.ExpressApp.MemberLevelSecurity.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.AdditionalViewControlsProvider ".\Xpand\Xpand.ExpressApp.Modules\AdditionalViewControlsProvider\Xpand.ExpressApp.AdditionalViewControlsProvider.csproj"
call buildproject.cmd Xpand.ExpressApp.AdditionalViewControlsProvider.Win ".\Xpand\Xpand.ExpressApp.Modules\AdditionalViewControlsProvider.Win\Xpand.ExpressApp.AdditionalViewControlsProvider.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.AdditionalViewControlsProvider.Web ".\Xpand\Xpand.ExpressApp.Modules\AdditionalViewControlsProvider.Web\Xpand.ExpressApp.AdditionalViewControlsProvider.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.ModelDifference ".\Xpand\Xpand.ExpressApp.Modules\ModelDifference\Xpand.ExpressApp.ModelDifference.csproj"
call buildproject.cmd Xpand.ExpressApp.ModelDifference.Win ".\Xpand\Xpand.ExpressApp.Modules\ModelDifference.Win\Xpand.ExpressApp.ModelDifference.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.ModelDifference.Web ".\Xpand\Xpand.ExpressApp.Modules\ModelDifference.Web\Xpand.ExpressApp.ModelDifference.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.FilterDataStore ".\Xpand\Xpand.ExpressApp.Modules\FilterDataStore\Xpand.ExpressApp.FilterDataStore.csproj"
call buildproject.cmd Xpand.ExpressApp.FilterDataStore.Win ".\Xpand\Xpand.ExpressApp.Modules\FilterDataStore.Win\Xpand.ExpressApp.FilterDataStore.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.FilterDataStore.Web ".\Xpand\Xpand.ExpressApp.Modules\FilterDataStore.Web\Xpand.ExpressApp.FilterDataStore.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.ArtifactState ".\Xpand\Xpand.ExpressApp.Modules\ArtifactState\Xpand.ExpressApp.ArtifactState.csproj"
call buildproject.cmd Xpand.ExpressApp.ConditionalActionState ".\Xpand\Xpand.ExpressApp.Modules\ConditionalActionState\Xpand.ExpressApp.ConditionalActionState.csproj"
call buildproject.cmd Xpand.ExpressApp.ConditionalControllerState ".\Xpand\Xpand.ExpressApp.Modules\ConditionalControllerState\Xpand.ExpressApp.ConditionalControllerState.csproj"
call buildproject.cmd Xpand.ExpressApp.ModelArtifactState ".\Xpand\Xpand.ExpressApp.Modules\ModelArtifactState\Xpand.ExpressApp.ModelArtifactState.csproj"
call buildproject.cmd Xpand.ExpressApp.ModelArtifactState.Win ".\Xpand\Xpand.ExpressApp.Modules\ModelArtifactState.Win\Xpand.ExpressApp.ModelArtifactState.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.WizardUI.Win ".\Xpand\Xpand.ExpressApp.Modules\WizardUI.Win\Xpand.ExpressApp.WizardUI.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.ViewVariants ".\Xpand\Xpand.ExpressApp.Modules\ViewVariants\Xpand.ExpressApp.ViewVariants.csproj"
call buildproject.cmd Xpand.ExpressApp.MasterDetail ".\Xpand\Xpand.ExpressApp.Modules\MasterDetail\Xpand.ExpressApp.MasterDetail.csproj"
call buildproject.cmd Xpand.ExpressApp.MasterDetail.Win ".\Xpand\Xpand.ExpressApp.Modules\MasterDetail.Win\Xpand.ExpressApp.MasterDetail.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.TreeListEditors ".\Xpand\Xpand.ExpressApp.Modules\TreeListEditors\Xpand.ExpressApp.TreeListEditors.csproj"
call buildproject.cmd Xpand.ExpressApp.TreeListEditors.Web ".\Xpand\Xpand.ExpressApp.Modules\TreeListEditors.Web\Xpand.ExpressApp.TreeListEditors.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.TreeListEditors.Win ".\Xpand\Xpand.ExpressApp.Modules\TreeListEditors.Win\Xpand.ExpressApp.TreeListEditors.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.ExceptionHandling ".\Xpand\Xpand.ExpressApp.Modules\ExceptionHandling\Xpand.ExpressApp.ExceptionHandling.csproj"
call buildproject.cmd Xpand.ExpressApp.ExceptionHandling.Win ".\Xpand\Xpand.ExpressApp.Modules\ExceptionHandling.Win\Xpand.ExpressApp.ExceptionHandling.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.ExceptionHandling.Web ".\Xpand\Xpand.ExpressApp.Modules\ExceptionHandling.Web\Xpand.ExpressApp.ExceptionHandling.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.WorldCreator ".\Xpand\Xpand.ExpressApp.Modules\WorldCreator\Xpand.ExpressApp.WorldCreator.csproj"
call buildproject.cmd Xpand.ExpressApp.WorldCreator.SqlDBMapper ".\Xpand\Xpand.ExpressApp.Modules\WorldCreator.SqlDBMapper\Xpand.ExpressApp.WorldCreator.SqlDBMapper.csproj"
call buildproject.cmd Xpand.ExpressApp.WorldCreator.Win ".\Xpand\Xpand.ExpressApp.Modules\WorldCreator.Win\Xpand.ExpressApp.WorldCreator.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.WorldCreator.Web ".\Xpand\Xpand.ExpressApp.Modules\WorldCreator.Web\Xpand.ExpressApp.WorldCreator.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.IO ".\Xpand\Xpand.ExpressApp.Modules\IO\Xpand.ExpressApp.IO.csproj"
call buildproject.cmd Xpand.ExpressApp.IO.Win ".\Xpand\Xpand.ExpressApp.Modules\IO.Win\Xpand.ExpressApp.IO.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.IO.Web ".\Xpand\Xpand.ExpressApp.Modules\IO.Web\Xpand.ExpressApp.IO.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.PivotChart ".\Xpand\Xpand.ExpressApp.Modules\PivotChart\Xpand.ExpressApp.PivotChart.csproj"
call buildproject.cmd Xpand.ExpressApp.PivotChart.Win ".\Xpand\Xpand.ExpressApp.Modules\PivotChart.Win\Xpand.ExpressApp.PivotChart.Win.csproj"
call buildproject.cmd Xpand.ExpressApp.PivotChart.Web ".\Xpand\Xpand.ExpressApp.Modules\PivotChart.Web\Xpand.ExpressApp.PivotChart.Web.csproj"
call buildproject.cmd Xpand.NCarousel ".\Xpand\Xpand.ExpressApp.Modules\NCarousel\Xpand.NCarousel.csproj"
call buildproject.cmd Xpand.ExpressApp.NCarousel.Web ".\Xpand\Xpand.ExpressApp.Modules\NCarousel.Web\Xpand.ExpressApp.NCarousel.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.Thumbnail.Web ".\Xpand\Xpand.ExpressApp.Modules\Thumbnail.Web\Xpand.ExpressApp.Thumbnail.Web.csproj"
call buildproject.cmd Xpand.ExpressApp.ConditionalDetailViews ".\Xpand\Xpand.ExpressApp.Modules\ConditionalDetailViews\Xpand.ExpressApp.ConditionalDetailViews.csproj"
call buildproject.cmd Xpand.ExpressApp.JobScheduler ".\Xpand\Xpand.ExpressApp.Modules\JobScheduler\Xpand.ExpressApp.JobScheduler.csproj"
call buildproject.cmd Xpand.Persistent.BaseImpl ".\Xpand\Xpand.Persistent\Xpand.Persistent.BaseImpl\Xpand.Persistent.BaseImpl.csproj"
call buildproject.cmd Xpand.ExpressApp.JobScheduler.Jobs ".\Xpand\Xpand.ExpressApp.Modules\JobScheduler.Jobs\Xpand.ExpressApp.JobScheduler.Jobs.csproj"


echo Building FeatureCenter.Base...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\FeatureCenter.Base\FeatureCenter.Base.csproj"
echo Building FeatureCenter.Module...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\FeatureCenter.Module\FeatureCenter.Module.csproj"
echo Building FeatureCenter.Module.Win...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\FeatureCenter.Module.Win\FeatureCenter.Module.Win.csproj"
echo Building FeatureCenter.Module.Web...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\FeatureCenter.Module.Web\FeatureCenter.Module.Web.csproj"
echo Building FeatureCenter.Win...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\FeatureCenter.Win\FeatureCenter.Win.csproj"
echo Building FeatureCenter.Web...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\FeatureCenter.Web\FeatureCenter.Web.csproj"
echo Building ExternalApplication.Module.Win...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\ExternalApplication\ExternalApplication.Module.Win\ExternalApplication.Module.Win.csproj"
echo Building ExternalApplication.Win...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\FeatureCenter\ExternalApplication\ExternalApplication.Win\ExternalApplication.Win.csproj"

echo Building Xpand.ExpressApp.ModelEditor...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\Xpand.Addins\Xpand.ExpressApp.ModelEditor\Xpand.ExpressApp.ModelEditor.csproj"
echo Building XpandAddIns...
%msbuild% /nologo /t:Rebuild /verbosity:quiet /p:Configuration=%configuration% ".\Xpand.Addins\XpandAddIns.csproj"
