//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// SessionKeepAliveReconnect class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class SessionKeepAliveReconnect {
}
