using System;
using System.Collections.Generic;
using System.Linq;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo.DB;
using eXpand.Persistent.Base.PersistentMetaData;
using eXpand.Persistent.Base.PersistentMetaData.PersistentAttributeInfos;
using Microsoft.SqlServer.Management.Smo;
using eXpand.ExpressApp.Core;
using eXpand.ExpressApp.WorldCreator.Core;

namespace eXpand.ExpressApp.WorldCreator.SqlDBMapper {
    public class AttributeMapper {
        readonly ObjectSpace _objectSpace;

        readonly DataTypeMapper _dataTypeMapper;

        public AttributeMapper(ObjectSpace objectSpace,DataTypeMapper dataTypeMapper) {
            _objectSpace = objectSpace;
            _dataTypeMapper = dataTypeMapper;
        }



        public List<IPersistentAttributeInfo> Create(Column column,IPersistentMemberInfo owner) {
            var persistentAttributeInfos = new List<IPersistentAttributeInfo>();
            if (owner.CodeTemplateInfo.CodeTemplate.TemplateType==TemplateType.XPOneToOnePropertyMember)
                return persistentAttributeInfos;
            if (column.InPrimaryKey){
                if (owner.Owner.CodeTemplateInfo.CodeTemplate.TemplateType != TemplateType.Struct) {
                    persistentAttributeInfos.Add(GetPersistentKeyAttribute(column));
                    persistentAttributeInfos.Add(_objectSpace.CreateWCObject<IPersistentPersistentAttribute>());
                }
            }
            if (!column.Nullable && !column.InPrimaryKey){
                persistentAttributeInfos.Add(GetPersistentRuleRequiredFieldAttribute(column));
            }
            if (_dataTypeMapper.GetDataType(column) == DBColumnType.String){
                persistentAttributeInfos.Add(GetPersistentSizeAttribute(column));
            }
            if ((column.IsForeignKey && !(column.InPrimaryKey)) || ((owner.Owner.CodeTemplateInfo.CodeTemplate.TemplateType == TemplateType.Struct && column.InPrimaryKey)))
                persistentAttributeInfos.Add(GetPersistentAssociationAttribute(column));
            return persistentAttributeInfos;
        }

        IPersistentAssociationAttribute GetPersistentAssociationAttribute(Column column) {
            var persistentAssociationAttribute = _objectSpace.CreateWCObject<IPersistentAssociationAttribute>();
            persistentAssociationAttribute.AssociationName = GetForeignKeyName(column.Name, (Table) column.Parent);
            return persistentAssociationAttribute;
        }

        IPersistentSizeAttribute GetPersistentSizeAttribute(Column column) {
            var persistentSizeAttribute = _objectSpace.CreateWCObject<IPersistentSizeAttribute>();
            persistentSizeAttribute.Size = column.DataType.MaximumLength;
            return persistentSizeAttribute;
        }

        IPersistentRuleRequiredFieldAttribute GetPersistentRuleRequiredFieldAttribute(Column column) {
            var persistentRuleRequiredFieldAttribute = _objectSpace.CreateWCObject<IPersistentRuleRequiredFieldAttribute>();
            persistentRuleRequiredFieldAttribute.Context = DefaultContexts.Save.ToString();
            persistentRuleRequiredFieldAttribute.ID = "RuleRequired for " + column.Name + " at " +
                                                      ((Table) column.Parent).Name;
            return persistentRuleRequiredFieldAttribute;
        }

        IPersistentKeyAttribute GetPersistentKeyAttribute(Column column) {
            var persistentAttributeInfo = _objectSpace.CreateWCObject<IPersistentKeyAttribute>();
            persistentAttributeInfo.AutoGenerated = column.Identity;
            return persistentAttributeInfo;
        }

        string GetForeignKeyName(string name, Table table)
        {
            var foreignTableName = (from ForeignKey key in table.ForeignKeys
                                    from ForeignKeyColumn column in key.Columns
                                    where column.Name == name
                                    select key.Name).FirstOrDefault();
            if (foreignTableName != null)
                return foreignTableName;
            throw new NotImplementedException(table.Name + " " + name);
        }

        public ObjectSpace ObjectSpace {
            get { return _objectSpace; }
        }
    }
}