'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class DialogPage

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ProgressControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

    '''<summary>
    '''UPVH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPVH As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''viewImageControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewImageControl As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

    '''<summary>
    '''viewCaptionControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCaptionControl As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

    '''<summary>
    '''UPEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPEI As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''ErrorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableRow5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow5 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''UPSAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPSAC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''SearchActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''TableRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''ViewSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSite As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''UPVSC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPVSC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''viewSiteControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewSiteControl1 As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

    '''<summary>
    '''TableRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow3 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''UPACH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPACH As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''actionContainerHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionContainerHolder As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder
End Class
