#DropDB SystemTesterEasyTest
#Application SystemTester.Win

*UseModel
*Action Log On
*Action Navigation(Default.Application Exit Object)

*ActionAvailable Refresh
*ActionAvailable Application Exit
*Action Application Exit(MinimizeOnExit) 
!ActionAvailable Application Exit
*ActionAvailable Refresh

*Action Log Off
!ActionAvailable Log Off
*Action Log On

*Action Edit Model
!ActionAvailable Edit Model

