#IncludeFile .\Init.inc
*Action Navigation(PreventDataLoading.FilterByText)

*Action Filter by Text(eXpandFramework)
*CheckTable 
 RowCount = 1
*Action Filter by Text()

*Action Filter(CommonFilter)
*CheckTable 
 RowCount = 1
*Action Filter by Text(eXpandFramework)
*CheckTable 
 RowCount = 0
*Action Filter by Text() 

*Action Filter(All)
*CheckTable 
 RowCount = 3
*Action Filter by Text(eXpandFramework)
*CheckTable 
 RowCount = 1
