;#IncludeFile .\Init.inc
*Navigate SequenceGenerator.Sequence Generator Object

*Action New(Sequence Generator Object)
*XpandFillForm
 Prefix = A
*SaveAndClose
*XpandProcessRecord
 Prefix = A
 Sequence = 0
*Navigate SequenceGenerator.Sequence Generator Object

*Action New(Sequence Generator Object)
*XpandFillForm
 Prefix = A
*SaveAndClose
*XpandProcessRecord
 Prefix = A
 Sequence = 1
*Navigate SequenceGenerator.Sequence Generator Object

