#IncludeFile .\Init.inc

*Action Navigation(Default.Navigation Items Object)
*Action New
*FillForm
 Name = Visible1
*Action Save and Close
*Action Navigation(Default.Navigation Items Object)
*Action New
*FillForm
 Name = Visible2
*Action Save and Close
*Action Navigation(Default.Navigation Items Object)
*Action New
*FillForm
 Name = Hidden
*Action Save and Close
*Action Navigation(NavigationItems.Group.Visible1)
*Action Navigation(NavigationItems.Group.Visible2)
!Action Navigation(NavigationItems.Group.Hidden)




