#IncludeFile .\Init.inc

*Action Navigation(NavigationItems.Navigation Items Object)
*Action New(Navigation Items Object)
*FillForm
 Name = Visible1
*Action Save and Close
*Action New(Navigation Items Object)
*FillForm
 Name = Visible2
*Action Save and Close
*Action New(Navigation Items Object)
*FillForm
 Name = Hidden
*Action Save and Close
*Action Navigation(NavigationItems.Group.Visible1)
*Action Navigation(NavigationItems.Group.Visible2)
!Action Navigation(NavigationItems.Group.Hidden)




