'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class [Default]

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''GE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GE As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

    '''<summary>
    '''ProgressControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

    '''<summary>
    '''UPPopupWindowControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPPopupWindowControl As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''PopupWindowControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupWindowControl As Global.DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl

    '''<summary>
    '''LogoLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TIC As Global.DevExpress.ExpressApp.Web.Controls.ThemedImageControl

    '''<summary>
    '''UPSAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPSAC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''SAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''UPNTAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPNTAC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''NTAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationTabsActionContainer

    '''<summary>
    '''UPLP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPLP As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''VTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VTC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''DAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''UPTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPTB As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''TB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''UPVH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPVH As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''VIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIC As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

    '''<summary>
    '''VCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VCC As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

    '''<summary>
    '''VHC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VHC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

    '''<summary>
    '''RNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RNC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''UPEMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPEMA As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''EMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMA As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''UPEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPEI As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''ErrorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

    '''<summary>
    '''UPVSC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPVSC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''VSC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VSC As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

    '''<summary>
    '''EditModeActions2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditModeActions2 As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''UPQC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPQC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''QC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.QuickAccessNavigationActionContainer

    '''<summary>
    '''UPIMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPIMP As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

    '''<summary>
    '''InfoMessagesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AIC As Global.DevExpress.ExpressApp.Web.Controls.AboutInfoControl
End Class
