#DropDB MasterDetailTesterEasyTest
#Application MasterDetailTester.Win
*UseModel MasterDetailLayoutView;..\CommonModel
*ScreenCapture
*LogOn

*Navigate Project
*Action New
*FillForm
 Name = eXpandFramework
*Action Contributors.New
*FillForm
 Name = Tolis Bekiaris
*Action Save and Close
*Action Save and Close
*Navigate Project

*Action Master Detail
*CheckTable
 Columns = Detail View Type
 Row = XpandXafLayoutView
