using System.ComponentModel;
using DevExpress.Xpo;
using eXpand.Persistent.Base.PersistentMetaData;
using eXpand.Persistent.Base.PersistentMetaData.PersistentAttributeInfos;

namespace eXpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos
{
    [WCRegistrator(typeof(IPersistentKeyAttribute))]
    [DefaultProperty("KeyName")]
    public class PersistentKeyAttribute:PersistentAttributeInfo, IPersistentKeyAttribute {
        public PersistentKeyAttribute(Session session) : base(session) {
        }
        [Browsable(false)]
        [MemberDesignTimeVisibility(false)]
        public string KeyName
        {
            get { return "Key"; }
        }

        private bool _autoGenerated;

        public bool AutoGenerated {
            get { return _autoGenerated; }
            set { SetPropertyValue("AutoGenerated", ref _autoGenerated, value); }
        }
        public override AttributeInfo Create() {
            return new AttributeInfo(typeof(KeyAttribute).GetConstructor(new[]{typeof(bool)}), new object[]{AutoGenerated});
        }
    }
}
