;#IncludeFile .\Init.inc

*Action New(Detail View Caching Object)
*Action Close
*HandleDialog
 Respond = No
*CheckActionsHint
 Delete[0] = DetailViewCachingObject_DetailView Called 1
*Action New(Detail View Caching Object)
*Action Close
*HandleDialog
 Respond = No
*CheckActionsHint
 Delete[0] = DetailViewCachingObject_DetailView Called 1

*Action Detail View Caching(NewModalWindow)
*Action Close
*HandleDialog
 Respond = No
*CheckActionsHint
 Delete[0] = DetailViewCachingObject_DetailView Called 1
