// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.192
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xpand.VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSXpandPackageString = "fa1289e0-6376-4d19-98c5-9d0c90dd3283";
        public const string guidVSXpandPackageCmdSetString = "6c0bd9dc-4a51-4a9d-8952-c5a69f472eab";
        public const string easyTestContextCommandSetString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public const string easyTestToolbarCommandSetString = "7b1b96be-b83b-4ed4-aea2-9ec8bbf7506a";
        public static Guid guidVSXpandPackage = new Guid(guidVSXpandPackageString);
        public static Guid guidVSXpandPackageCmdSet = new Guid(guidVSXpandPackageCmdSetString);
        public static Guid easyTestContextCommandSet = new Guid(easyTestContextCommandSetString);
        public static Guid easyTestToolbarCommandSet = new Guid(easyTestToolbarCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidKillIISExpress = 0x010E;
        public const int EasyTestToolbarCmdSetGroup = 0x010D;
        public const int XpandTopLevelMenu = 0x010B;
        public const int SolutionExplorerCmdSetGroup = 0x010A;
        public const int EasyTestContextMenuCmdSetGroup = 0x0109;
        public const int XpandMenuGroup = 0x0107;
        public const int cmdidDebugEasyTest = 0x0100;
        public const int cmdidRunEasyTest = 0x0101;
        public const int cmdidDropDatabase = 0x0102;
        public const int cmdidLoadProjectFromreference = 0x0103;
        public const int cmdidLoadProjectFromreferenceTool = 0x010C;
        public const int cmdidProjectConverter = 0x0104;
        public const int cmdidExploreXAFErrors = 0x0105;
        public const int cmdidShowMEToolbox = 0x0106;
        public const int ContextMenu = 0x040D;
        public const int Toolbar = 0x1012;
    }
}
