namespace Xpand.Persistent.Base.PersistentMetaData.PersistentAttributeInfos {
    public interface IPersistentKeyAttribute:IPersistentAttributeInfo
    {
        bool AutoGenerated { get; set; }
    }
}