//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// DefaultVertical class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class DefaultVertical
{

    /// <summary>
    /// ProgressControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.ProgressControl ProgressControl;

    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    /// <summary>
    /// LogoLink control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink LogoLink;

    /// <summary>
    /// LogoImage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image LogoImage;

    /// <summary>
    /// SecurityActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer SecurityActionContainer;

    /// <summary>
    /// VerticalNewActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer VerticalNewActionContainer;

    /// <summary>
    /// SearchActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer SearchActionContainer;

    /// <summary>
    /// NavigationBarActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer NavigationBarActionContainer;

    /// <summary>
    /// ToolsRoundPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel ToolsRoundPanel;

    /// <summary>
    /// PanelContent1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxRoundPanel.PanelContent PanelContent1;

    /// <summary>
    /// VerticalToolsActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer VerticalToolsActionContainer;

    /// <summary>
    /// ViewsHistoryNavigationContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer ViewsHistoryNavigationContainer;

    /// <summary>
    /// ViewImage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image ViewImage;

    /// <summary>
    /// ViewCaptionLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label ViewCaptionLabel;

    /// <summary>
    /// ToolBar control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder ToolBar;

    /// <summary>
    /// ContextObjectsCreationActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer ContextObjectsCreationActionContainer;

    /// <summary>
    /// TopRecordEditActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer TopRecordEditActionContainer;

    /// <summary>
    /// RecordsNavigationContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer RecordsNavigationContainer;

    /// <summary>
    /// ViewPresentationActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer ViewPresentationActionContainer;

    /// <summary>
    /// ListViewDataManagementActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer ListViewDataManagementActionContainer;

    /// <summary>
    /// ErrorInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl ErrorInfo;

    /// <summary>
    /// Table1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Table Table1;

    /// <summary>
    /// TableRow2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TableRow TableRow2;

    /// <summary>
    /// ViewSite control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TableCell ViewSite;

    /// <summary>
    /// NavigationLinksActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationLinksActionContainer NavigationLinksActionContainer;

    /// <summary>
    /// Copyright control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal Copyright;

    /// <summary>
    /// DiagnosticActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer DiagnosticActionContainer;

    /// <summary>
    /// InfoMessagesPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal InfoMessagesPanel;
}
