//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// NestedFrameControl class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class NestedFrameControl
{

    /// <summary>
    /// ContextObjectsCreationActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer ContextObjectsCreationActionContainer;

    /// <summary>
    /// RecordEditContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer RecordEditContainer;

    /// <summary>
    /// ViewContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer ViewContainer;

    /// <summary>
    /// DiagnosticActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer DiagnosticActionContainer;

    /// <summary>
    /// FiltersActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer FiltersActionContainer;

    /// <summary>
    /// ViewImage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image ViewImage;

    /// <summary>
    /// ViewCaptionLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label ViewCaptionLabel;

    /// <summary>
    /// ViewSite control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ViewSite;
}
